server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:parceldeliverycost
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

voucher-service:
  url: http://mynt-exam.mocklab.io
  apikey: apikey

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    xyz:
      mynt:
        parceldeliverycost:
          integration: DEBUG